### ISSUE TITLE
🛑 Help Centre is down

### ISSUE THREAD

**Issue by EddiesTech** [teamcoldricalcs/status#7]
In [`06682c8`](https://github.com/teamcoldricalcs/status/commit/06682c8e0916e172d2bfaed62df36421a7a1c443
), Help Centre (https://help.coldricalcs.com) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by coldricalcs** [comment]
The cause of this outage is unknown and was fixed by restarting the host machine via an online dashboard. If you continue to experience issues, please email support@coldricalcs.com.

Eddie
